### ISSUE TITLE
0:1 variable domains not correctly solved

### ISSUE THREAD

**Issue by bboettch** [afriesen/rdis#4]
dear all,

given the following polynomial:
default = 0:1
1,x0
1,x1

gives:
'[...]
optimization result: 1 at (0.5, 0.5) -- bounds: [0, 2]
[...]'

while for domains -1e-15:1    and 0:1.00000000001
the result are -1e-15 at  (-1e-15,-1e-15) and 0 at (0,0) as expected

might this be relevant for non trivial examples, so that it is worth to be fixed?

bboettch

**Comment by bboettch** [comment]
I just noticed that it might be the related to the issue already stated in the README:

"If the minimum is on the border of the domain, RDIS will do poorly because it does not handle constraints properly (a non-infinite domain constitutes box constraints on the function)."

**Comment by afriesen** [comment]
Yes, this is most likely due to improperly handling box constraints during gradient descent. I believe that using a descent method that respects the box constraints would remedy this problem, if you're interested in extending the code.
